### ISSUE TITLE
Bug: duplicate code completion suggestions in templates

### ISSUE THREAD

**Issue by nevadascout** [nathansbradshaw/zed-angular#10]
I'm seeing duplicate code completion suggestions in the template (2 for each). Maybe the LSP is running twice 🤔 

<img width="729" alt="Screenshot 2024-10-22 at 12 40 56" src="https://github.com/user-attachments/assets/45910fbf-85cc-4cdc-8957-3a362a38d8ec">

<img width="435" alt="Screenshot 2024-10-22 at 12 57 06" src="https://github.com/user-attachments/assets/59faf472-207e-48c6-abb4-69c744c5211c">

**Comment by jpike88** [comment]
This is still a problem for me, can this issue be reopened

<img width="672" alt="Image" src="https://github.com/user-attachments/assets/96d72cf2-9abb-475d-833f-fca28b39a54d" />

**Comment by jpike88** [comment]
that might not be a problem with this plugn actually. ignore last msg

**Comment by jpike88** [comment]
I found the problem for me, it was this bizarre default behaviour of both typescript-language-server with vtsls kicking in at same time... not sure which one is better but it fixed any duplicating behaviour

https://zed.dev/docs/languages/typescript#language-servers
