### ISSUE TITLE
Angular extension cannot be installed in Fedora Linux

### ISSUE THREAD

**Issue by PanosMagic32** [nathansbradshaw/zed-angular#17]
Following the instructions from the README.md, I clonned the repo, opened the "Install Dev Extension", I chose the project folder but nothing happened.
I found the following log in the `~/.local/share/zed/logs`:
`[INFO] compiling Rust extension ~/Documents/zed-angular
[ERROR] failed to compile Rust extension
Caused by:
    0: failed to run rustc
    1: No such file or directory (os error 2)
`
Any ideas?

**Comment by kyjus25** [comment]
Do you have rustc installed? `rustc --version`

**Comment by PanosMagic32** [comment]
Sorry for the late response!
I wasn't aware you needed Rust to compile the extension in order to be installed. I installed Rust and everything worked fine.
Thanks!
